package supabase:cfd1-fdw@0.1.0;

world cfd1 {
    import supabase:wrappers/http@0.1.0;
    import supabase:wrappers/jwt@0.1.0;
    import supabase:wrappers/stats@0.1.0;
    import supabase:wrappers/time@0.1.0;
    import supabase:wrappers/utils@0.1.0;
    export supabase:wrappers/routines@0.1.0;
}
