[workspace]
members = [
    "supabase-wrappers",
    "supabase-wrappers-macros",
    "wrappers",
    "wasm-wrappers/fdw/cal_fdw",
    "wasm-wrappers/fdw/calendly_fdw",
    "wasm-wrappers/fdw/cfd1_fdw",
    "wasm-wrappers/fdw/clerk_fdw",
    "wasm-wrappers/fdw/helloworld_fdw",
    "wasm-wrappers/fdw/hubspot_fdw",
    "wasm-wrappers/fdw/infura_fdw",
    "wasm-wrappers/fdw/langfuse_fdw",
    "wasm-wrappers/fdw/notion_fdw",
    "wasm-wrappers/fdw/openapi_fdw",
    "wasm-wrappers/fdw/orb_fdw",
    "wasm-wrappers/fdw/paddle_fdw",
    "wasm-wrappers/fdw/shopify_fdw",
    "wasm-wrappers/fdw/slack_fdw",
    "wasm-wrappers/fdw/snowflake_fdw",
]
default-members = ["supabase-wrappers", "supabase-wrappers-macros", "wrappers"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.97.1"
homepage = "https://github.com/supabase/wrappers"
repository = "https://github.com/supabase/wrappers"

[profile.dev]
panic = "unwind"
lto = "thin"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 16
