use std::fs;
use std::path::Path;

fn main() {
    // Generated unconditionally (regardless of the s3vectors_fdw feature) so that
    // OUT_DIR always has this file, no matter which feature set a given build-script
    // invocation resolves — e.g. rust-analyzer's build-script-data loading pass can
    // land on a different feature context than its cfg-evaluated diagnostics pass,
    // otherwise leading it to report the include!() in s3vec.rs as unresolvable
    // even though the module is only ever compiled when the feature is on.
    generate_s3vec_type_sql();
    generate_event_triggers_sql();
}

/// Generates `s3vec_type_sql.rs` in OUT_DIR, which contains the `pgrx::extension_sql!` call
/// for the S3Vec type with the correct versioned library name embedded as a string literal.
///
/// This indirection is necessary because `pgrx::extension_sql!` requires a string literal
/// (not a macro expression like `concat!(env!(...), ...)`), but we need the library name
/// (e.g. "wrappers-0.6.0") to be derived from the crate version at compile time.
///
/// The generated file is included in `s3vec.rs` via:
///   `include!(concat!(env!("OUT_DIR"), "/s3vec_type_sql.rs"));`
fn generate_s3vec_type_sql() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let pkg_name = std::env::var("CARGO_PKG_NAME").expect("CARGO_PKG_NAME not set");
    let pkg_version = std::env::var("CARGO_PKG_VERSION").expect("CARGO_PKG_VERSION not set");
    let lib_name = format!("{pkg_name}-{pkg_version}");

    // The outer r##"..."## delimiter allows r#"..."# to appear inside the format string.
    let content = format!(
        r##"// @generated by build.rs — do not edit by hand.
// Library name "{lib_name}" is embedded at compile time from CARGO_PKG_NAME/VERSION.
pgrx::extension_sql!(
    r#"DO $s3vec_upgrade$
BEGIN
    -- 1. Shell type (must exist before the in/out functions reference it)
    BEGIN
        CREATE TYPE S3Vec;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;

    -- 2. Input function
    BEGIN
        CREATE OR REPLACE FUNCTION "s3vec_in"("input" cstring)
            RETURNS S3Vec
            IMMUTABLE PARALLEL SAFE
            LANGUAGE c
            AS '{lib_name}', 's3vec_in_wrapper';
    EXCEPTION WHEN duplicate_function THEN NULL;
    END;

    -- 3. Output function
    BEGIN
        CREATE OR REPLACE FUNCTION "s3vec_out"("input" S3Vec)
            RETURNS cstring
            IMMUTABLE STRICT PARALLEL SAFE
            LANGUAGE c
            AS '{lib_name}', 's3vec_out_wrapper';
    EXCEPTION WHEN duplicate_function THEN NULL;
    END;

    -- 4. Complete type definition (must come after in/out functions)
    BEGIN
        CREATE TYPE S3Vec (
            INTERNALLENGTH = variable,
            INPUT = s3vec_in,
            OUTPUT = s3vec_out,
            STORAGE = extended
        );
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;

    -- 5. s3vec_knn function
    -- PostgreSQL has no CREATE OR REPLACE OPERATOR, so we manage the function
    -- and operator together here with EXCEPTION WHEN to make upgrades idempotent.
    BEGIN
        CREATE OR REPLACE FUNCTION "s3vec_knn"("_left" S3Vec, "_right" S3Vec)
            RETURNS bool
            IMMUTABLE STRICT PARALLEL SAFE
            LANGUAGE c
            AS '{lib_name}', 's3vec_knn_wrapper';
    EXCEPTION WHEN duplicate_function THEN NULL;
    END;

    -- 6. s3vec_knn operator (<==> for S3Vec)
    BEGIN
        CREATE OPERATOR <==> (
            PROCEDURE = "s3vec_knn",
            LEFTARG = S3Vec,
            RIGHTARG = S3Vec
        );
    EXCEPTION WHEN duplicate_function THEN NULL;
    END;

    -- 7. metadata_filter function
    BEGIN
        CREATE OR REPLACE FUNCTION "metadata_filter"("_left" jsonb, "_right" jsonb)
            RETURNS bool
            IMMUTABLE STRICT PARALLEL SAFE
            LANGUAGE c
            AS '{lib_name}', 'metadata_filter_wrapper';
    EXCEPTION WHEN duplicate_function THEN NULL;
    END;

    -- 8. metadata_filter operator (<==> for jsonb)
    BEGIN
        CREATE OPERATOR <==> (
            PROCEDURE = "metadata_filter",
            LEFTARG = jsonb,
            RIGHTARG = jsonb
        );
    EXCEPTION WHEN duplicate_function THEN NULL;
    END;
END
$s3vec_upgrade$;
"#,
    name = "s3vec_type",
    // S3Vec's type identity is already owned by `#[derive(PostgresType)]` in
    // s3vec.rs (even with `#[pgrx(sql = false)]`, which only suppresses the
    // emitted CREATE TYPE text, not the graph registration). Declaring
    // `Type(S3Vec)` here too causes pgrx 0.19's schema generator to reject it
    // as "type ident ... matched multiple SQL entities" — only the functions
    // this block defines need to be declared here.
    creates = [Function(s3vec_knn), Function(metadata_filter)],
);
"##
    );

    let out_path = Path::new(&out_dir).join("s3vec_type_sql.rs");
    fs::write(&out_path, content)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));
}

/// Generates `event_triggers_sql.rs` in OUT_DIR, which contains the `pgrx::extension_sql!`
/// call registering `check_supported_column_types` (the event trigger from
/// `event_triggers.rs`) with the correct versioned library name embedded as a string
/// literal. Same indirection as `generate_s3vec_type_sql`, same reason.
///
/// The generated file is included in `event_triggers.rs` via:
///   `include!(concat!(env!("OUT_DIR"), "/event_triggers_sql.rs"));`
fn generate_event_triggers_sql() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let pkg_name = std::env::var("CARGO_PKG_NAME").expect("CARGO_PKG_NAME not set");
    let pkg_version = std::env::var("CARGO_PKG_VERSION").expect("CARGO_PKG_VERSION not set");
    let lib_name = format!("{pkg_name}-{pkg_version}");

    // The outer r##"..."## delimiter allows r#"..."# to appear inside the format string.
    let content = format!(
        r##"// @generated by build.rs — do not edit by hand.
// Library name "{lib_name}" is embedded at compile time from CARGO_PKG_NAME/VERSION.
pgrx::extension_sql!(
    r#"DO $register_event_triggers$
BEGIN

    -- 1. Check supported types function
    -- no OR REPLACE guard needed (never raises duplicate_function); no
    -- IMMUTABLE/STRICT/PARALLEL SAFE either, since none of them are true here
    CREATE OR REPLACE FUNCTION "check_supported_column_types"()
        RETURNS event_trigger
        LANGUAGE c
        AS '{lib_name}', 'check_supported_column_types';

    -- 2. Register event trigger
    -- 'ALTER TABLE' is needed too: Postgres tags `ALTER TABLE <foreign_table> ADD COLUMN`
    -- (the common way to alter a foreign table) as 'ALTER TABLE', not 'ALTER FOREIGN TABLE'.
    BEGIN
        CREATE EVENT TRIGGER check_supported_column_types
            ON ddl_command_end
            WHEN TAG IN ('CREATE FOREIGN TABLE', 'ALTER FOREIGN TABLE', 'ALTER TABLE')
            EXECUTE FUNCTION check_supported_column_types();
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
END
$register_event_triggers$;
"#,
    name = "register_event_triggers",
    creates = [Function(check_supported_column_types)],
);
"##
    );

    let out_path = Path::new(&out_dir).join("event_triggers_sql.rs");
    fs::write(&out_path, content)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));
}
