[package]
name = "supabase-wrappers"
version = "0.1.28"
authors = ["Supabase Inc. https://supabase.com/"]
license = "Apache-2.0"
description = "Postgres Foreign Data Wrapper development framework in Rust."
homepage = "https://github.com/supabase/wrappers/tree/main/supabase-wrappers"
repository = "https://github.com/supabase/wrappers/tree/main/supabase-wrappers"
categories = ["database"]
keywords = ["database", "postgres", "postgresql", "extension"]
edition = { workspace = true }
rust-version = { workspace = true }

[features]
default = ["pg15"]
pg13 = ["pgrx/pg13"]
pg14 = ["pgrx/pg14"]
pg15 = ["pgrx/pg15"]
pg16 = ["pgrx/pg16"]
pg17 = ["pgrx/pg17"]
pg18 = ["pgrx/pg18"]

[dependencies]
pgrx = { version = "=0.19.2", default-features = false }
thiserror = "1.0.63"
tokio = { version = "1.43", features = ["rt", "net"] }
uuid = { version = "1.10.0" }
supabase-wrappers-macros = { version = "0.1", path = "../supabase-wrappers-macros" }

[package.metadata.docs.rs]
features = ["pg15"]
no-default-features = true
# Enable `#[cfg(docsrs)]` (https://docs.rs/about/builds#cross-compiling)
rustc-args = ["--cfg", "docsrs"]
