name: Deploy docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/catalog/**"

permissions: {}

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    env:
      DOCS_REVALIDATION_KEY: ${{ secrets.DOCS_REVALIDATION_KEY }}
    steps:
      - name: Request docs revalidation
        run: |
          curl -X POST https://supabase.com/docs/api/revalidate \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.DOCS_REVALIDATION_KEY }}' \
            -d '{"tags": ["wrappers"]}'
