name: Publish to crates.io

on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish-to-crates-io:
    name: Publish to crates.io
    runs-on: blacksmith-4vcpu-ubuntu-2404
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          toolchain: 1.97.1

      - run: |
          sudo apt remove -y postgres*
          sudo apt -y install curl ca-certificates build-essential pkg-config libssl-dev
          sudo install -d /usr/share/postgresql-common/pgdg
          sudo curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
          . /etc/os-release
          sudo sh -c "echo 'deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $VERSION_CODENAME-pgdg main' > /etc/apt/sources.list.d/pgdg.list"
          sudo apt update -y -qq --fix-missing
          sudo apt -y install postgresql-client-15 postgresql-15 postgresql-server-dev-15
          sudo apt -y autoremove && sudo apt -y clean
          sudo chmod a+rwx `/usr/lib/postgresql/15/bin/pg_config --pkglibdir` `/usr/lib/postgresql/15/bin/pg_config --sharedir`/extension /var/run/postgresql/

      - run: cargo install --locked cargo-pgrx --version 0.19.2
      - run: cargo pgrx init --pg15 /usr/lib/postgresql/15/bin/pg_config

      - uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec # v1.0.3
        id: auth

      - name: Check and publish supabase-wrappers-macros
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          VERSION=$(cargo metadata --format-version 1 --no-deps --offline | jq -r '.packages[] | select(.name == "supabase-wrappers-macros") | .version')
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" --user-agent "supabase-wrappers" https://crates.io/api/v1/crates/supabase-wrappers-macros/$VERSION)
          if [ "$STATUS" = "404" ]; then
            cargo publish -p supabase-wrappers-macros
          else
            echo "Version $VERSION already published, skipping."
          fi

      # sleep for a while to avoid crates.io request rate limit
      - name: Sleep for 2 seconds
        run: sleep 2s

      - name: Check and publish supabase-wrappers
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          VERSION=$(cargo metadata --format-version 1 --no-deps --offline | jq -r '.packages[] | select(.name == "supabase-wrappers") | .version')
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" --user-agent "supabase-wrappers" https://crates.io/api/v1/crates/supabase-wrappers/$VERSION)
          if [ "$STATUS" = "404" ]; then
            cargo publish -p supabase-wrappers
          else
            echo "Version $VERSION already published, skipping."
          fi
